server:
  port: 8081


spring:
  batch:
    jdbc:
      initialize-schema: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  datasource:
#    url: jdbc:mariadb://localhost:8081/batch?useUnicode=true&characterEncoding=UTF8&useSSL=false
#    username: root
#    password: mariadb
#    driver-class-name: org.mariadb.jdbc.Driver

  h2:
    console:
      enabled: true
      path: /h2-console